//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderToCook
    {
        public int ShiftId { get; set; }
        public int OrderId { get; set; }
        public bool IsCompleted { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
